services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: ALX_prodev  
      MYSQL_USER: alx
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"                        # expose port to host
    volumes:
      - mysql_data:/var/lib/mysql          # persist data between restarts

volumes:
  mysql_data:
