apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  labels:
    app: messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app-container
          image: samuelikoli/messaging-app:1.0   # CHANGE THIS
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "messagingapp.settings"
            - name: PYTHONUNBUFFERED
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  type: ClusterIP     # Internal-only service
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000         # Internal cluster port
      targetPort: 8000   # Django app port
