apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green
  labels:
    app: messaging-app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      containers:
        - name: messaging-app-container
          # TODO: change this to your real image & tag for the GREEN (new) version
          image: your-dockerhub-username/messaging-app:v2
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "messagingapp.settings"
            - name: PYTHONUNBUFFERED
              value: "1"
